name: Deploy Angular to Firebase Hosting

on:
  push:
    branches: [ "main" ]  # Cambia si usas otra rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'  # Usa la versión de tu proyecto

      - run: npm ci

      - run: |
          echo "export const environment = {
            production: true,
            baseUrl: '${{ secrets.API_URL_PROD }}'  # Secret con la URL de tu API en producción
          };" > src/environments/environment.prod.ts

      # Paso 5: Build del proyecto Angular
      - run: npm run build -- --configuration production

      # Paso 6: Desplegar en Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: live  # Canal de producción
